### ISSUE TITLE
ECMAScript 6 not looking very good in PHPStorm

### ISSUE THREAD

**Issue by bensampaio** [craft-tyler/brogrammer-theme-phpstorm#2]
I'm not sure if this is a problem with PHPStorm or the theme but the colors are not looking very good for ES6. In Sublime Text they look good, though... I noticed the following:
- `from` keyword is not highlighted
- functions in class don't have a different color
- import and export have the same color as var, let and const
- everything looks too much white and blue (colors in Sublime Text look way nicer);

**Comment by craft-tyler** [comment]
@bensampaio 

I pushed up an update to some styles for PhpStorm 10.  Let me know if you see anything else you would like changed.  

Unfortunately PhpStorm's not as granular when it comes to editing those styles so I got it the best I could...

If you are still seeing some issue please add a screenshot.

**Comment by bensampaio** [comment]
Thanks a lot @craft-tyler! It looks a lot better but I still get a few weird things like the one bellow:

<img width="409" alt="screen shot 2016-01-16 at 20 07 12" src="https://cloud.githubusercontent.com/assets/1700178/12373958/f59a7f6a-bc8c-11e5-8710-b12e1081b753.png">

The variable, the functions and the arguments are all white...

**Comment by craft-tyler** [comment]
@bensampaio, I'm not familiar with ecmascript 6... Does phpstorm support this natively?  How can I recreate that?

**Comment by bensampaio** [comment]
Yes, ES6 is supported by PHPStorm. You can set it on the JavaScript settings as shown below:

<img width="1050" alt="screen shot 2016-01-17 at 16 30 02" src="https://cloud.githubusercontent.com/assets/1700178/12378223/be7ebefa-bd37-11e5-8985-7248162487c5.png">

To try the situation I posted before you can use the following code:

``` js
import { externalVar } from 'some_js_file';

const PRIVATE_CONST = '';
export const PUBLIC_CONST = '';

export default class ExportedClass {

    constructor({ argVar }) {
        let privateVar = PRIVATE_CONST;

        argVar.toString();

        externalVar.toString();

        privateVar.toString();

        this.publicVar = PUBLIC_CONST;

    }

    get publicVar() {
        return this.public;
    }

    set publicVar(value) {
        this.public = value;
    }

    test() {
        return this.public;
    }
}
```

With brogrammer it displays like this:

<img width="337" alt="screen shot 2016-01-17 at 16 43 53" src="https://cloud.githubusercontent.com/assets/1700178/12378304/a726f5c2-bd39-11e5-9536-9bf2cb8d679f.png">

In this example `externalVar`, `publicVar`, `argVar` and `privateVar` are all variables but they have different colors. Besides that, the white ones conflict with the functions color, which is also white. Also the `publicVar` function is grey but it shouldn't because it is being used on this line `this.publicVar = PUBLIC_CONST;`.
