### ISSUE TITLE
has issue in PHPStorm 10.0.2

### ISSUE THREAD

**Issue by mehrancodes** [craft-tyler/brogrammer-theme-phpstorm#3]
Hi.
I didn't tried this theme until today i installed it on phpstorm 10.0.2.
Background of editor is white. I fixed it
But there is a lot of other colors to change so the theme be All Darken like in Sublime text.
e.g, background color of Gutter [#3E434C] that is not so nice with this theme and settings sidebar color also .etc

This theme is so beauty in Sublime text because it's all Darken!
Please change colors :+1:  :)

**Comment by craft-tyler** [comment]
@rasulian 

I've updated the repo to reflect the changes for PHPStorm 10... I've also added some styles for the gutter colors.  Good call!
